### ISSUE TITLE
svgPanZoom dependency

### ISSUE THREAD

**Issue by dankimio** [StephanWagner/svgMap#3]
Right now I'm getting the following error: `ReferenceError: Can't find variable: svgPanZoom`.

svgPanZoom is not declared as a dependency.

**Comment by StephanWagner** [comment]
It's a dev dependency. It will get added automatically. Not sure how this would work with your webpack setup. Feel free to send me some code so I can debug.

**Comment by dankimio** [comment]
It will not load in production, since it's not dev environment.

**Comment by StephanWagner** [comment]
It depends on it, but it will get added to the final file with gulp. When using the files from the dist folder svgPanZoom will get loaded automatically.

I'm not sure if that's best practice and I'd be glad for suggestions.

**Comment by xaja** [comment]
so, i install it via npm 
`npm install svgmap`

add in vuejs project (that use webpack):
`import svgMap from 'svgMap';`
`import 'svgmap/dist/svgMap.min.css';`

the map appears(!). but there is a error in console: 
`ReferenceError: svgPanZoom is not defined`
and map is broken.

but if i try to include script just in <head><script src="pathToYourScriptInCDN"></script></head> (not via import) —  everything is good. why? what am i doing wrong?

**Comment by StephanWagner** [comment]
Sounds like a bug.

svgMap and svgPanZoom use UMD https://github.com/umdjs/umd.

When svgMap gets built I'm just adding svgPanZoom.js to the top of the build file. Probably not the best solution :/

**Comment by leastbad** [comment]
@xaja @StephanWagner @dankimio

I'm sorry for any rudeness, but it was clear that the package author was not planning on modernizing the codebase to work with build systems. I just needed it to work, so I refactored the codebase and released my forked version as [svgmap-next](https://www.npmjs.com/package/svgmap-next) on npm.

This resolves all issues with the `svg-pan-zoom` dependency.

I also changed it so that the `options` now accepts `element` instead of `targetElementID`.

```js
import svgMap from 'svgmap-next'

const map = new svgMap({
  element: this.element
})
```

I'm not planning on maintaining this; again, I just needed it to *work*. That said, if anyone reading this finds it helpful, I'm glad. Thanks to the library author for doing all of the actual hard work!

**Comment by StephanWagner** [comment]
I just released v2.0.3 which should fix this. Feel free to test and comment.

Thanks @leastbad for creating svgmap-next. I fixed it with a different approach though. I updated the umd wrapper to include svg-pan-zoom correctly.

This means that when svgMap will get installed via CDN or HTML script, svg-pan-zoom needs to be included first. Readme is updated.

**Comment by leastbad** [comment]
The whole point of what I did is that I need a standard webpack import to work. If script tags work for you, awesome!

**Comment by StephanWagner** [comment]
Yeah, the fix should also fix the webpack import. I used Snowpack in `demo/es6/` and there the standard import is working now. Feel free to provide a webpack config for me to test.

**Comment by StephanWagner** [comment]
Closing as it should work properly now.
